name: Documentation

on:
  release:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache/pip
          restore-keys: |
            mkdocs-material-
      - run: pip install -r .github/workflows/mkdocs-requirements.txt
      - run: mkdocs gh-deploy --force


#name: Documentation
#
#on:
#  push:
#    branches:
#      - main
#  workflow_dispatch:
#
#permissions:
#  contents: write
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    timeout-minutes: 60
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Validate Gradle Wrapper
#        uses: gradle/wrapper-validation-action@v1
#
#      - name: Setup JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Cache Gradle packages
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Run Dokka Task
#        uses: gradle/gradle-build-action@v2
#        with:
#          cache-read-only: true
#          arguments: dokkaHtml
#
#      - name: Deploy Documentations
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: convention/build/dokka/html
